on: push
name: Check code style

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Run rustfmt
        run: cargo fmt --all

      - name: Run clippy linter
        run: cargo clippy --fix --workspace --all-targets --all-features --allow-dirty

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Fix clippy lints
