name: Check code style

on:
  pull_request:
    paths:
      - ".github/workflows/lint.yml"
      - "Cargo.*"
      - "src/**"
      - "lorax/**"
      - "dialect/**"
      - "tests/**"
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run rustfmt check
        run: cargo fmt --all --check

      - name: Run clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main
      
      - name: Install cargo-shear
        run: cargo binstall --no-confirm cargo-shear
      
      - name: Run cargo-shear
        run: cargo shear
